### PR TITLE
fix: style

### PR DESCRIPTION
**Pull request by daflyinbed**
before:
image
after:
image

### CODE REVIEW

**Comment by sxzz** [comment]
Can't see the difference from your screenshot. 🤔

**Comment by Boshen** [comment]
It had overscroll-auto, hence the horizontal scrollbar. But yeah, it should be pointed out instead of "find the difference".

**Comment by daflyinbed** [comment]
Sorry for the "find the difference".
1. The 8px bottom padding caused the scrollbars to be misaligned, which is very noticeable on my screen. 
image
2. `overflow-auto` will prevent the browser from displaying scrollbars when they're not needed.
image

**Review by sxzz — APPROVED** [review]

**Comment by sxzz** [comment]
Thanks!

**Pull request merged**
