### PR TITLE
feat: add demo code 

### PR DESCRIPTION
**Pull request by eryue0220**
This pr include:
* support url to record code;
* suppoert syntax check;

### CODE REVIEW

**Comment by Boshen** [comment]
Error: src/utils/url.ts(3,22): error TS7016: Could not find a declaration file for module 'lzma/src/lzma_worker.js'.

**Comment by eryue0220** [comment]
> Error: src/utils/url.ts(3,22): error TS7016: Could not find a declaration file for module 'lzma/src/lzma_worker.js'.

I've updated to another package `fflate`.

**Comment by eryue0220** [comment]
›   Error: Site not found. Please rerun "netlify link"

Seems occur an error when deploy netlify.

**Comment by Boshen** [comment]
Thank you, I'll fix the issue with deploying netlify from a fork.

**Pull request merged**
