### PR TITLE
feat: add playground website layout

### PR DESCRIPTION
**Pull request by eryue0220**
This pr is part of the new playground, and it just added layout and theme,  and a new sidebar for the oxc configurations. 
image
image

### CODE REVIEW

**Comment by Boshen** [comment]
Should we be using a component library? What is the source of the included components?

**Comment by Boshen** [comment]
I see a warning: `[@vue/compiler-sfc] `defineProps` is a compiler macro and no longer needs to be imported.`

**Comment by Boshen** [comment]
@Dunqing please take a look, I think you want to use some specific libraries?

**Comment by Dunqing** [comment]
> Should we be using a component library? 

I think we should be. The component library can save a lot of time. Also, headless-ui components is easy to modify. 

> What is the source of the included components?

I'm sorry, I don't understand what you're asking.

**Comment by Dunqing** [comment]
I prefer to use `UnoCSS` instead of `TailwindCSS`. The UnoCSS has a lot of presets we can use.  Like [unocss-preset-theme](https://github.com/unpreset/unocss-preset-theme) preset can help us quickly support light/dark themes. But I'm not sure if this can work well with `shadcn-vue`.

**Comment by Boshen** [comment]
Let's try https://github.com/radix-vue/shadcn-vue, we would be dog fooding ourselves as well https://github.com/radix-vue/shadcn-vue/blob/63bb21808fb36e04e32f8462cb2aef47082d98f9/packages/module/package.json#L39

**Comment by Boshen** [comment]
@eryue0220 Can you take a look at [shadcn-vue](https://github.com/radix-vue/shadcn-vue) and see if you can replace this PR's component usage with it?

**Comment by eryue0220** [comment]
> @eryue0220 Can you take a look at [shadcn-vue](https://github.com/radix-vue/shadcn-vue) and see if you can replace this PR's component usage with it?

Yes, I used [shadcn-vue](https://www.shadcn-vue.com/docs/introduction), but it's a little different. The components' code will be installed in the repo instead of `node_modules`. And in this project, the `shadcn-vue` components' code was installed in `src/ui`, and the `src/component/ui` just wrap some business code based on it.

**Review by Boshen — APPROVED** [review]
Thank you, let's ship and iterate.

**Pull request merged**
